import { createStitches } from "@stitches/react";

export const { styled, css } = createStitches({
  theme: {
    colors: {
      cardButtonBg: "#1F3540",
      cardButtonShadow: "#112029",
      genericButtonBg: "#A8BEC9",
      genericButtonShadow: "#718C99",
      x_color: "#31C4BE",
      o_color: "#F2B237",
      dark_text: "#172B35",
      light_text: "#A8BEC9",
      board_bg: "#192A32",
    },
    space: {
      0: "0px",
      1: "8px",
      2: "16px",
      3: "24px",
      4: "32px",
      5: "40px",
      6: "48px",
      7: "56px",
      8: "64px",
      9: "72px",
      10: "80px",
    },
    fontSizes: {
      0: "0px",
      1: "8px",
      2: "16px",
      3: "24px",
      4: "32px",
      5: "40px",
      6: "48px",
      7: "56px",
      8: "64px",
      9: "72px",
      10: "80px",
    },
    fonts: {
      untitled: "Untitled Sans, apple-system, sans-serif",
      mono: "Söhne Mono, menlo, monospace",
    },
    radii: {
      card: "25px",
    },
    shadows: {
      0: "0px 8px",
    },
    fontWeights: {},
    lineHeights: {},
    letterSpacings: {},
    sizes: {},
    borderWidths: {},
    borderStyles: {},
    zIndices: {},
    transitions: {},
  },
});
